name = "namesys-w3name"
main = "dist/index.mjs"
compatibility_date = "2023-10-16"

[build]
command = "npm run build"

[[migrations]]
tag = "v1"
new_classes = ["NameRoom0", "IPNSRecord"]

# For the dev environment. The "durable_objects" section is not shared among environments though.
[durable_objects]
  bindings = [
    { name = "NAME_ROOM", class_name = "NameRoom0" },
    { name = "IPNS_RECORD", class_name = "IPNSRecord" }
  ]


[vars]
REBROADCAST_INTERVAL_MS = "600000"
PUBLISHER_ENDPOINT_URL = "http://localhost:8000" # http://95.217.178.38 | https://pub.namesys.xyz:8000
PUBLISHER_AUTH_SECRET = "hellonamesys"

# Test
[env.test.vars]
REBROADCAST_INTERVAL_MS = "500"
PUBLISHER_ENDPOINT_URL = "http://localhost:8000" # http://95.217.178.38 | https://pub.namesys.xyz:8000
PUBLISHER_AUTH_SECRET = "hellonamesys"

[env.test.durable_objects]
  bindings = [
    { name = "NAME_ROOM", class_name = "NameRoom0" },
    { name = "IPNS_RECORD", class_name = "IPNSRecord" }
  ]

# Staging
[env.staging]
account_id = "892973ecf5177f94c0bc003d89f498b6" # NameSys CF account
routes = [
  { pattern = "https://stage.namesys.xyz/*", zone_id = "6d058d8a7f0f52bd3bfc840a638f5199" }
]
vars = { ENV = "staging", REBROADCAST_INTERVAL_MS = "86400000" }
[env.staging.durable_objects]
  bindings = [
    { name = "NAME_ROOM", class_name = "NameRoom0" },
    { name = "IPNS_RECORD", class_name = "IPNSRecord" }
  ]

# Production
[env.production]
account_id = "892973ecf5177f94c0bc003d89f498b6" # NameSys CF account
routes = [
  { pattern = "https://ipns.namesys.xyz/*", zone_id = "6d058d8a7f0f52bd3bfc840a638f5199" }
]
vars = { ENV = "production", REBROADCAST_INTERVAL_MS = "86400000" }
[env.production.durable_objects]
  bindings = [
    { name = "NAME_ROOM", class_name = "NameRoom0" },
    { name = "IPNS_RECORD", class_name = "IPNSRecord" }
  ]

# The necessary secrets are:
# - PUBLISHER_ENDPOINT_URL
# - PUBLISHER_AUTH_SECRET
# - LOGTAIL_TOKEN
# - SENTRY_DSN
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these
