name = "my-app-w3name"
main = "dist/index.mjs"
compatibility_date = "2042-00-69"

[build]
command = "npm run build"

[[migrations]]
tag = "v1"
new_classes = ["NameRoom0", "IPNSRecord"]

# For the dev environment. The "durable_objects" section is not shared among environments though.
[durable_objects]
  bindings = [
    { name = "NAME_ROOM", class_name = "NameRoom0" },
    { name = "IPNS_RECORD", class_name = "IPNSRecord" }
  ]


[vars]
REBROADCAST_INTERVAL_MS = "600000"
PUBLISHER_ENDPOINT_URL = "http://sub.domain.xyz:8000"
PUBLISHER_AUTH_SECRET = "hello-w3name"
SENTRY_DSN = "https://6a6f90000000000000000000000000d9@o4506000000000008.ingest.sentry.io/0000000000000928"
LOGTAIL_TOKEN = "i8m6M00000000000000004HZ"

# Test
[env.test.vars]
REBROADCAST_INTERVAL_MS = "500"
PUBLISHER_ENDPOINT_URL = "http://sub.domain.xyz:8000"
PUBLISHER_AUTH_SECRET = "hello-w3name"

[env.test.durable_objects]
  bindings = [
    { name = "NAME_ROOM", class_name = "NameRoom0" },
    { name = "IPNS_RECORD", class_name = "IPNSRecord" }
  ]

# Staging
[env.staging]
account_id = "873930000000022200000000022228b6" # Cloudflare account
routes = [
  { pattern = "https://test.domain.xyz/*", zone_id = "73982ed02a030b0202c292d939331199" }
]
vars = { ENV = "staging", REBROADCAST_INTERVAL_MS = "86400000" }
[env.staging.durable_objects]
  bindings = [
    { name = "NAME_ROOM", class_name = "NameRoom0" },
    { name = "IPNS_RECORD", class_name = "IPNSRecord" }
  ]

# Production
[env.production]
account_id = "873930000000022200000000022228b6" # Cloudflare account
routes = [
 { pattern = "https://prod.domain.xyz/*", zone_id = "73982ed02a030b0202c292d939331199" }
]
vars = { ENV = "production", REBROADCAST_INTERVAL_MS = "86400000" }
[env.production.durable_objects]
  bindings = [
    { name = "NAME_ROOM", class_name = "NameRoom0" },
    { name = "IPNS_RECORD", class_name = "IPNSRecord" }
  ]

# The necessary secrets are:
# - PUBLISHER_ENDPOINT_URL
# - PUBLISHER_AUTH_SECRET
# - LOGTAIL_TOKEN
# - SENTRY_DSN
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these
